version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: first-principles-docs:dev
    container_name: first-principles-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      # Mount the source code for hot-reloading
      - ./app:/app
      # Prevent node_modules from being overwritten by the host's
      - /app/node_modules
    networks:
      - app-network
    # Resource limits for development (can be adjusted)
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

networks:
  app-network:
    driver: bridge
