export type ThemeOption = {
  name: string;
  category: string;
  background: string;
  foreground: string;
  primary: string;
  primaryForeground: string;
  secondary: string;
  secondaryForeground: string;
  border: string;
  cardBg: string;
  cardForeground: string;
  mutedForeground: string;
  accentForeground: string;
  popoverForeground: string;
};

export const themes: ThemeOption[] = [
  // Modern Dark Themes
  {
    name: "GitHub Dark",
    category: "Modern Dark",
    background: "#0d1117",
    foreground: "#f0f6fc",
    primary: "#58a6ff",
    primaryForeground: "#ffffff",
    secondary: "#21262d",
    secondaryForeground: "#f0f6fc",
    border: "#30363d",
    cardBg: "#161b22",
    cardForeground: "#f0f6fc",
    mutedForeground: "#8b949e",
    accentForeground: "#f0f6fc",
    popoverForeground: "#f0f6fc",
  },
  {
    name: "Linear Dark",
    category: "Modern Dark",
    background: "#0c0d0e",
    foreground: "#ffffff",
    primary: "#5e6ad2",
    primaryForeground: "#ffffff",
    secondary: "#1a1b1e",
    secondaryForeground: "#ffffff",
    border: "#2a2d31",
    cardBg: "#151618",
    cardForeground: "#ffffff",
    mutedForeground: "#9ca3af",
    accentForeground: "#ffffff",
    popoverForeground: "#ffffff",
  },
  {
    name: "Notion Dark",
    category: "Modern Dark",
    background: "#191919",
    foreground: "#ffffff",
    primary: "#2eaadc",
    primaryForeground: "#ffffff",
    secondary: "#2f2f2f",
    secondaryForeground: "#ffffff",
    border: "#373737",
    cardBg: "#242424",
    cardForeground: "#ffffff",
    mutedForeground: "#9b9b9b",
    accentForeground: "#ffffff",
    popoverForeground: "#ffffff",
  },
  {
    name: "VS Code Dark+",
    category: "Developer",
    background: "#1e1e1e",
    foreground: "#d4d4d4",
    primary: "#007acc",
    primaryForeground: "#ffffff",
    secondary: "#2d2d30",
    secondaryForeground: "#d4d4d4",
    border: "#3e3e42",
    cardBg: "#252526",
    cardForeground: "#d4d4d4",
    mutedForeground: "#969696",
    accentForeground: "#d4d4d4",
    popoverForeground: "#d4d4d4",
  },
  {
    name: "Dracula",
    category: "Developer",
    background: "#282a36",
    foreground: "#f8f8f2",
    primary: "#bd93f9",
    primaryForeground: "#282a36",
    secondary: "#44475a",
    secondaryForeground: "#f8f8f2",
    border: "#6272a4",
    cardBg: "#2d2f3a",
    cardForeground: "#f8f8f2",
    mutedForeground: "#6272a4",
    accentForeground: "#f8f8f2",
    popoverForeground: "#f8f8f2",
  },
  {
    name: "Tokyo Night",
    category: "Developer",
    background: "#1a1b26",
    foreground: "#a9b1d6",
    primary: "#7aa2f7",
    primaryForeground: "#1a1b26",
    secondary: "#24283b",
    secondaryForeground: "#a9b1d6",
    border: "#414868",
    cardBg: "#1f2335",
    cardForeground: "#a9b1d6",
    mutedForeground: "#565f89",
    accentForeground: "#a9b1d6",
    popoverForeground: "#a9b1d6",
  },
  {
    name: "Catppuccin Mocha",
    category: "Modern Dark",
    background: "#1e1e2e",
    foreground: "#cdd6f4",
    primary: "#89b4fa",
    primaryForeground: "#1e1e2e",
    secondary: "#313244",
    secondaryForeground: "#cdd6f4",
    border: "#45475a",
    cardBg: "#181825",
    cardForeground: "#cdd6f4",
    mutedForeground: "#6c7086",
    accentForeground: "#cdd6f4",
    popoverForeground: "#cdd6f4",
  },
  {
    name: "Arc Dark",
    category: "Modern Dark",
    background: "#2f343f",
    foreground: "#d3dae3",
    primary: "#5294e2",
    primaryForeground: "#ffffff",
    secondary: "#383c4a",
    secondaryForeground: "#d3dae3",
    border: "#4b5162",
    cardBg: "#353945",
    cardForeground: "#d3dae3",
    mutedForeground: "#8b9dc3",
    accentForeground: "#d3dae3",
    popoverForeground: "#d3dae3",
  },

  // Modern Light Themes
  {
    name: "GitHub Light",
    category: "Modern Light",
    background: "#ffffff",
    foreground: "#24292f",
    primary: "#0969da",
    primaryForeground: "#ffffff",
    secondary: "#f6f8fa",
    secondaryForeground: "#24292f",
    border: "#d0d7de",
    cardBg: "#f6f8fa",
    cardForeground: "#24292f",
    mutedForeground: "#656d76",
    accentForeground: "#24292f",
    popoverForeground: "#24292f",
  },
  {
    name: "Linear Light",
    category: "Modern Light",
    background: "#ffffff",
    foreground: "#000000",
    primary: "#5e6ad2",
    primaryForeground: "#ffffff",
    secondary: "#f7f8f9",
    secondaryForeground: "#000000",
    border: "#e1e5e9",
    cardBg: "#fafbfc",
    cardForeground: "#000000",
    mutedForeground: "#6b7280",
    accentForeground: "#000000",
    popoverForeground: "#000000",
  },
  {
    name: "Notion Light",
    category: "Modern Light",
    background: "#ffffff",
    foreground: "#37352f",
    primary: "#2eaadc",
    primaryForeground: "#ffffff",
    secondary: "#f7f6f3",
    secondaryForeground: "#37352f",
    border: "#e9e9e7",
    cardBg: "#fbfbfa",
    cardForeground: "#37352f",
    mutedForeground: "#787774",
    accentForeground: "#37352f",
    popoverForeground: "#37352f",
  },
  {
    name: "Figma Light",
    category: "Modern Light",
    background: "#ffffff",
    foreground: "#1e1e1e",
    primary: "#0d99ff",
    primaryForeground: "#ffffff",
    secondary: "#f5f5f5",
    secondaryForeground: "#1e1e1e",
    border: "#e6e6e6",
    cardBg: "#f9f9f9",
    cardForeground: "#1e1e1e",
    mutedForeground: "#666666",
    accentForeground: "#1e1e1e",
    popoverForeground: "#1e1e1e",
  },
  {
    name: "Apple Light",
    category: "Modern Light",
    background: "#ffffff",
    foreground: "#1c1c1e",
    primary: "#007aff",
    primaryForeground: "#ffffff",
    secondary: "#f2f2f7",
    secondaryForeground: "#1c1c1e",
    border: "#d1d1d6",
    cardBg: "#f9f9f9",
    cardForeground: "#1c1c1e",
    mutedForeground: "#8e8e93",
    accentForeground: "#1c1c1e",
    popoverForeground: "#1c1c1e",
  },
  {
    name: "Tailwind Light",
    category: "Modern Light",
    background: "#ffffff",
    foreground: "#111827",
    primary: "#3b82f6",
    primaryForeground: "#ffffff",
    secondary: "#f9fafb",
    secondaryForeground: "#111827",
    border: "#e5e7eb",
    cardBg: "#f3f4f6",
    cardForeground: "#111827",
    mutedForeground: "#6b7280",
    accentForeground: "#111827",
    popoverForeground: "#111827",
  },

  // Minimal Themes
  {
    name: "Pure Dark",
    category: "Minimal",
    background: "#000000",
    foreground: "#ffffff",
    primary: "#ffffff",
    primaryForeground: "#000000",
    secondary: "#1a1a1a",
    secondaryForeground: "#ffffff",
    border: "#333333",
    cardBg: "#0d0d0d",
    cardForeground: "#ffffff",
    mutedForeground: "#a0a0a0",
    accentForeground: "#ffffff",
    popoverForeground: "#ffffff",
  },
  {
    name: "Pure Light",
    category: "Minimal",
    background: "#ffffff",
    foreground: "#000000",
    primary: "#000000",
    primaryForeground: "#ffffff",
    secondary: "#f8f8f8",
    secondaryForeground: "#000000",
    border: "#e0e0e0",
    cardBg: "#fcfcfc",
    cardForeground: "#000000",
    mutedForeground: "#666666",
    accentForeground: "#000000",
    popoverForeground: "#000000",
  },
  {
    name: "Monospace Dark",
    category: "Minimal",
    background: "#0a0a0a",
    foreground: "#f5f5f5",
    primary: "#00ff00",
    primaryForeground: "#000000",
    secondary: "#1a1a1a",
    secondaryForeground: "#f5f5f5",
    border: "#2a2a2a",
    cardBg: "#121212",
    cardForeground: "#f5f5f5",
    mutedForeground: "#888888",
    accentForeground: "#f5f5f5",
    popoverForeground: "#f5f5f5",
  },

  // Focus Themes
  {
    name: "Deep Focus",
    category: "Focus",
    background: "#1a1a1a",
    foreground: "#e8e8e8",
    primary: "#4a9eff",
    primaryForeground: "#ffffff",
    secondary: "#2a2a2a",
    secondaryForeground: "#e8e8e8",
    border: "#3a3a3a",
    cardBg: "#222222",
    cardForeground: "#e8e8e8",
    mutedForeground: "#999999",
    accentForeground: "#e8e8e8",
    popoverForeground: "#e8e8e8",
  },
  {
    name: "Zen Mode",
    category: "Focus",
    background: "#f8f9fa",
    foreground: "#2d3748",
    primary: "#4299e1",
    primaryForeground: "#ffffff",
    secondary: "#edf2f7",
    secondaryForeground: "#2d3748",
    border: "#e2e8f0",
    cardBg: "#ffffff",
    cardForeground: "#2d3748",
    mutedForeground: "#718096",
    accentForeground: "#2d3748",
    popoverForeground: "#2d3748",
  },

  // High Contrast
  {
    name: "High Contrast Dark",
    category: "High Contrast",
    background: "#000000",
    foreground: "#ffffff",
    primary: "#00ffff",
    primaryForeground: "#000000",
    secondary: "#1a1a1a",
    secondaryForeground: "#ffffff",
    border: "#666666",
    cardBg: "#0a0a0a",
    cardForeground: "#ffffff",
    mutedForeground: "#cccccc",
    accentForeground: "#ffffff",
    popoverForeground: "#ffffff",
  },
  {
    name: "High Contrast Light",
    category: "High Contrast",
    background: "#ffffff",
    foreground: "#000000",
    primary: "#0000ff",
    primaryForeground: "#ffffff",
    secondary: "#f0f0f0",
    secondaryForeground: "#000000",
    border: "#888888",
    cardBg: "#f8f8f8",
    cardForeground: "#000000",
    mutedForeground: "#333333",
    accentForeground: "#000000",
    popoverForeground: "#000000",
  },

  // Nature & Calm
  {
    name: "Forest Night",
    category: "Nature",
    background: "#1b2b1b",
    foreground: "#e8f5e8",
    primary: "#4ade80",
    primaryForeground: "#000000",
    secondary: "#2a3b2a",
    secondaryForeground: "#e8f5e8",
    border: "#3a4b3a",
    cardBg: "#1f2e1f",
    cardForeground: "#e8f5e8",
    mutedForeground: "#94a3b8",
    accentForeground: "#e8f5e8",
    popoverForeground: "#e8f5e8",
  },
  {
    name: "Ocean Blue",
    category: "Nature",
    background: "#1e2a3a",
    foreground: "#e0f2fe",
    primary: "#38bdf8",
    primaryForeground: "#ffffff",
    secondary: "#2a3b4a",
    secondaryForeground: "#e0f2fe",
    border: "#3a4b5a",
    cardBg: "#243240",
    cardForeground: "#e0f2fe",
    mutedForeground: "#94a3b8",
    accentForeground: "#e0f2fe",
    popoverForeground: "#e0f2fe",
  },
  {
    name: "Sunset Warm",
    category: "Warm",
    background: "#2a1f1f",
    foreground: "#fef2e8",
    primary: "#fb923c",
    primaryForeground: "#ffffff",
    secondary: "#3a2a2a",
    secondaryForeground: "#fef2e8",
    border: "#4a3a3a",
    cardBg: "#322727",
    cardForeground: "#fef2e8",
    mutedForeground: "#d1d5db",
    accentForeground: "#fef2e8",
    popoverForeground: "#fef2e8",
  },
];

export const themeCategories = [
  {
    name: "Modern Dark",
    icon: "🌙",
    description: "Contemporary dark themes with excellent readability",
  },
  {
    name: "Modern Light",
    icon: "☀️",
    description: "Clean, modern light themes for focused work",
  },
  {
    name: "Developer",
    icon: "💻",
    description: "Code editor inspired themes with perfect contrast",
  },
  {
    name: "Minimal",
    icon: "⚪",
    description: "Distraction-free themes for maximum focus",
  },
  {
    name: "Focus",
    icon: "🎯",
    description: "Specially designed for deep work and concentration",
  },
  {
    name: "High Contrast",
    icon: "⚫",
    description: "Maximum contrast for accessibility and clarity",
  },
  {
    name: "Nature",
    icon: "🌿",
    description: "Calming nature-inspired color palettes",
  },
  {
    name: "Warm",
    icon: "🔥",
    description: "Cozy, warm-toned themes for comfortable reading",
  },
];
